<?php

namespace Zawaj\FichesCandidatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomaineProfessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineProfessionRepository extends EntityRepository
{
}
