<?php

namespace Zawaj\FichesCandidatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnfantCandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantCandidatRepository extends EntityRepository
{
}
